### ISSUE TITLE
Add unaligned reads from primitive-unaligned

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/primitive#355] opened 2022-08-16 14:44 UTC
On architectures that support unaligned reads should you still use `readUnalignedByteArray` or can you just read normally? Should you always use the unaligned variants if there is a possibility that the index is not aligned?

**Comment by andrewthad** [comment] 2022-08-17 20:47
What are you referring to when you say "read normally"? There's no way to make `readByteArray` (from `primitive`) perform an unaligned read.

**Comment by oberblastmeister** [comment] 2022-08-19 21:53
Yeah I somehow got confused. I guess I was thinking about something like `memcpy` where it is cross platform but `readUnalignedByteArray` will fail on some architectures?

**Comment by andrewthad** [comment] 2023-09-01 18:16
Closing since I'm not certain what this issue is asking for. The issue title is a request for a change to the library, but the body of the issue is questions about how GHC works. Open a new issue if there's still something actionable you'd like to see done.

**Closed by andrewthad** 2023-09-01 18:16 UTC
